version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_banco
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: 'bot_ingles'
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  bot:
    build: .
    container_name: sarah_bot
    restart: always
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=bot_ingles